package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteEventParams creates a new DeleteEventParams object
// with the default values initialized.
func NewDeleteEventParams() *DeleteEventParams {
	var ()
	return &DeleteEventParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteEventParamsWithTimeout creates a new DeleteEventParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteEventParamsWithTimeout(timeout time.Duration) *DeleteEventParams {
	var ()
	return &DeleteEventParams{

		timeout: timeout,
	}
}

/*DeleteEventParams contains all the parameters to send to the API endpoint
for the delete event operation typically these are written to a http.Request
*/
type DeleteEventParams struct {

	/*Index*/
	Index string

	timeout time.Duration
}

// WithIndex adds the index to the delete event params
func (o *DeleteEventParams) WithIndex(index string) *DeleteEventParams {
	o.Index = index
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteEventParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
