package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd-redfish/models"
)

// NewDoResetParams creates a new DoResetParams object
// with the default values initialized.
func NewDoResetParams() *DoResetParams {
	var ()
	return &DoResetParams{}
}

/*DoResetParams contains all the parameters to send to the API endpoint
for the do reset operation typically these are written to a http.Request
*/
type DoResetParams struct {

	/*Identifier*/
	Identifier string
	/*Payload*/
	Payload *models.RackHDResetActionResetAction
}

// WithIdentifier adds the identifier to the do reset params
func (o *DoResetParams) WithIdentifier(identifier string) *DoResetParams {
	o.Identifier = identifier
	return o
}

// WithPayload adds the payload to the do reset params
func (o *DoResetParams) WithPayload(payload *models.RackHDResetActionResetAction) *DoResetParams {
	o.Payload = payload
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *DoResetParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if o.Payload == nil {
		o.Payload = new(models.RackHDResetActionResetAction)
	}

	if err := r.SetBodyParam(o.Payload); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
