package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewEventServiceRootParams creates a new EventServiceRootParams object
// with the default values initialized.
func NewEventServiceRootParams() *EventServiceRootParams {

	return &EventServiceRootParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewEventServiceRootParamsWithTimeout creates a new EventServiceRootParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewEventServiceRootParamsWithTimeout(timeout time.Duration) *EventServiceRootParams {

	return &EventServiceRootParams{

		timeout: timeout,
	}
}

/*EventServiceRootParams contains all the parameters to send to the API endpoint
for the event service root operation typically these are written to a http.Request
*/
type EventServiceRootParams struct {
	timeout time.Duration
}

// WriteToRequest writes these params to a swagger request
func (o *EventServiceRootParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
