package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetChassisParams creates a new GetChassisParams object
// with the default values initialized.
func NewGetChassisParams() *GetChassisParams {
	var ()
	return &GetChassisParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetChassisParamsWithTimeout creates a new GetChassisParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetChassisParamsWithTimeout(timeout time.Duration) *GetChassisParams {
	var ()
	return &GetChassisParams{

		timeout: timeout,
	}
}

/*GetChassisParams contains all the parameters to send to the API endpoint
for the get chassis operation typically these are written to a http.Request
*/
type GetChassisParams struct {

	/*Identifier*/
	Identifier string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the get chassis params
func (o *GetChassisParams) WithIdentifier(identifier string) *GetChassisParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetChassisParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
