package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetRegistryFileParams creates a new GetRegistryFileParams object
// with the default values initialized.
func NewGetRegistryFileParams() *GetRegistryFileParams {
	var ()
	return &GetRegistryFileParams{}
}

/*GetRegistryFileParams contains all the parameters to send to the API endpoint
for the get registry file operation typically these are written to a http.Request
*/
type GetRegistryFileParams struct {

	/*Identifier*/
	Identifier string
}

// WithIdentifier adds the identifier to the get registry file params
func (o *GetRegistryFileParams) WithIdentifier(identifier string) *GetRegistryFileParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetRegistryFileParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
