package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSchemaParams creates a new GetSchemaParams object
// with the default values initialized.
func NewGetSchemaParams() *GetSchemaParams {
	var ()
	return &GetSchemaParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSchemaParamsWithTimeout creates a new GetSchemaParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSchemaParamsWithTimeout(timeout time.Duration) *GetSchemaParams {
	var ()
	return &GetSchemaParams{

		timeout: timeout,
	}
}

/*GetSchemaParams contains all the parameters to send to the API endpoint
for the get schema operation typically these are written to a http.Request
*/
type GetSchemaParams struct {

	/*Identifier*/
	Identifier string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the get schema params
func (o *GetSchemaParams) WithIdentifier(identifier string) *GetSchemaParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSchemaParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
