package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetChassisParams creates a new GetChassisParams object
// with the default values initialized.
func NewGetChassisParams() *GetChassisParams {
	var ()
	return &GetChassisParams{}
}

/*GetChassisParams contains all the parameters to send to the API endpoint
for the get chassis operation typically these are written to a http.Request
*/
type GetChassisParams struct {

	/*Identifier*/
	Identifier string
}

// WithIdentifier adds the identifier to the get chassis params
func (o *GetChassisParams) WithIdentifier(identifier string) *GetChassisParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetChassisParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
