package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetThermalParams creates a new GetThermalParams object
// with the default values initialized.
func NewGetThermalParams() *GetThermalParams {
	var ()
	return &GetThermalParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetThermalParamsWithTimeout creates a new GetThermalParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetThermalParamsWithTimeout(timeout time.Duration) *GetThermalParams {
	var ()
	return &GetThermalParams{

		timeout: timeout,
	}
}

/*GetThermalParams contains all the parameters to send to the API endpoint
for the get thermal operation typically these are written to a http.Request
*/
type GetThermalParams struct {

	/*Identifier*/
	Identifier string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the get thermal params
func (o *GetThermalParams) WithIdentifier(identifier string) *GetThermalParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetThermalParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
