package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSessionInfoParams creates a new GetSessionInfoParams object
// with the default values initialized.
func NewGetSessionInfoParams() *GetSessionInfoParams {
	var ()
	return &GetSessionInfoParams{}
}

/*GetSessionInfoParams contains all the parameters to send to the API endpoint
for the get session info operation typically these are written to a http.Request
*/
type GetSessionInfoParams struct {

	/*Identifier*/
	Identifier string
}

// WithIdentifier adds the identifier to the get session info params
func (o *GetSessionInfoParams) WithIdentifier(identifier string) *GetSessionInfoParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSessionInfoParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
