package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSystemTasksParams creates a new GetSystemTasksParams object
// with the default values initialized.
func NewGetSystemTasksParams() *GetSystemTasksParams {
	var ()
	return &GetSystemTasksParams{}
}

/*GetSystemTasksParams contains all the parameters to send to the API endpoint
for the get system tasks operation typically these are written to a http.Request
*/
type GetSystemTasksParams struct {

	/*Identifier*/
	Identifier string
}

// WithIdentifier adds the identifier to the get system tasks params
func (o *GetSystemTasksParams) WithIdentifier(identifier string) *GetSystemTasksParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemTasksParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
