package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetEventParams creates a new GetEventParams object
// with the default values initialized.
func NewGetEventParams() *GetEventParams {
	var ()
	return &GetEventParams{}
}

/*GetEventParams contains all the parameters to send to the API endpoint
for the get event operation typically these are written to a http.Request
*/
type GetEventParams struct {

	/*Index*/
	Index string
}

// WithIndex adds the index to the get event params
func (o *GetEventParams) WithIndex(index string) *GetEventParams {
	o.Index = index
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetEventParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
