package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/httpkit"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd-redfish/models"
)

// GetManagerAccountsIdentifierReader is a Reader for the GetManagerAccountsIdentifier structure.
type GetManagerAccountsIdentifierReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the recieved o.
func (o *GetManagerAccountsIdentifierReader) ReadResponse(response client.Response, consumer httpkit.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetManagerAccountsIdentifierOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewGetManagerAccountsIdentifierBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewGetManagerAccountsIdentifierUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetManagerAccountsIdentifierForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewGetManagerAccountsIdentifierNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetManagerAccountsIdentifierInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, client.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetManagerAccountsIdentifierOK creates a GetManagerAccountsIdentifierOK with default headers values
func NewGetManagerAccountsIdentifierOK() *GetManagerAccountsIdentifierOK {
	return &GetManagerAccountsIdentifierOK{}
}

/*GetManagerAccountsIdentifierOK handles this case with default header values.

Success
*/
type GetManagerAccountsIdentifierOK struct {
	Payload *models.ManagerAccount100ManagerAccount
}

func (o *GetManagerAccountsIdentifierOK) Error() string {
	return fmt.Sprintf("[GET /ManagerAccounts/{identifier}][%d] getManagerAccountsIdentifierOK  %+v", 200, o.Payload)
}

func (o *GetManagerAccountsIdentifierOK) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ManagerAccount100ManagerAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetManagerAccountsIdentifierBadRequest creates a GetManagerAccountsIdentifierBadRequest with default headers values
func NewGetManagerAccountsIdentifierBadRequest() *GetManagerAccountsIdentifierBadRequest {
	return &GetManagerAccountsIdentifierBadRequest{}
}

/*GetManagerAccountsIdentifierBadRequest handles this case with default header values.

The request could not be processed because it contains missing or invalid information  (such as validation error on an input field, a missing required value, and so on).  An extended error shall be returned in the response body, as defined in section Extended  Error Handling.

*/
type GetManagerAccountsIdentifierBadRequest struct {
}

func (o *GetManagerAccountsIdentifierBadRequest) Error() string {
	return fmt.Sprintf("[GET /ManagerAccounts/{identifier}][%d] getManagerAccountsIdentifierBadRequest ", 400)
}

func (o *GetManagerAccountsIdentifierBadRequest) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetManagerAccountsIdentifierUnauthorized creates a GetManagerAccountsIdentifierUnauthorized with default headers values
func NewGetManagerAccountsIdentifierUnauthorized() *GetManagerAccountsIdentifierUnauthorized {
	return &GetManagerAccountsIdentifierUnauthorized{}
}

/*GetManagerAccountsIdentifierUnauthorized handles this case with default header values.

The authentication credentials included with this request are missing or invalid.

*/
type GetManagerAccountsIdentifierUnauthorized struct {
}

func (o *GetManagerAccountsIdentifierUnauthorized) Error() string {
	return fmt.Sprintf("[GET /ManagerAccounts/{identifier}][%d] getManagerAccountsIdentifierUnauthorized ", 401)
}

func (o *GetManagerAccountsIdentifierUnauthorized) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetManagerAccountsIdentifierForbidden creates a GetManagerAccountsIdentifierForbidden with default headers values
func NewGetManagerAccountsIdentifierForbidden() *GetManagerAccountsIdentifierForbidden {
	return &GetManagerAccountsIdentifierForbidden{}
}

/*GetManagerAccountsIdentifierForbidden handles this case with default header values.

The server recognized the credentials in the request, but those credentials do not  possess authorization to perform this request.

*/
type GetManagerAccountsIdentifierForbidden struct {
}

func (o *GetManagerAccountsIdentifierForbidden) Error() string {
	return fmt.Sprintf("[GET /ManagerAccounts/{identifier}][%d] getManagerAccountsIdentifierForbidden ", 403)
}

func (o *GetManagerAccountsIdentifierForbidden) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetManagerAccountsIdentifierNotFound creates a GetManagerAccountsIdentifierNotFound with default headers values
func NewGetManagerAccountsIdentifierNotFound() *GetManagerAccountsIdentifierNotFound {
	return &GetManagerAccountsIdentifierNotFound{}
}

/*GetManagerAccountsIdentifierNotFound handles this case with default header values.

The request specified a URI of a resource that does not exist.

*/
type GetManagerAccountsIdentifierNotFound struct {
}

func (o *GetManagerAccountsIdentifierNotFound) Error() string {
	return fmt.Sprintf("[GET /ManagerAccounts/{identifier}][%d] getManagerAccountsIdentifierNotFound ", 404)
}

func (o *GetManagerAccountsIdentifierNotFound) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGetManagerAccountsIdentifierInternalServerError creates a GetManagerAccountsIdentifierInternalServerError with default headers values
func NewGetManagerAccountsIdentifierInternalServerError() *GetManagerAccountsIdentifierInternalServerError {
	return &GetManagerAccountsIdentifierInternalServerError{}
}

/*GetManagerAccountsIdentifierInternalServerError handles this case with default header values.

Error
*/
type GetManagerAccountsIdentifierInternalServerError struct {
	Payload *models.ErrorResponse
}

func (o *GetManagerAccountsIdentifierInternalServerError) Error() string {
	return fmt.Sprintf("[GET /ManagerAccounts/{identifier}][%d] getManagerAccountsIdentifierInternalServerError  %+v", 500, o.Payload)
}

func (o *GetManagerAccountsIdentifierInternalServerError) readResponse(response client.Response, consumer httpkit.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
