package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSystemsIdentifierEthernetInterfacesIndexParams creates a new GetSystemsIdentifierEthernetInterfacesIndexParams object
// with the default values initialized.
func NewGetSystemsIdentifierEthernetInterfacesIndexParams() *GetSystemsIdentifierEthernetInterfacesIndexParams {
	var ()
	return &GetSystemsIdentifierEthernetInterfacesIndexParams{}
}

/*GetSystemsIdentifierEthernetInterfacesIndexParams contains all the parameters to send to the API endpoint
for the get systems identifier ethernet interfaces index operation typically these are written to a http.Request
*/
type GetSystemsIdentifierEthernetInterfacesIndexParams struct {

	/*Identifier*/
	Identifier string
	/*Index*/
	Index string
}

// WithIdentifier adds the identifier to the get systems identifier ethernet interfaces index params
func (o *GetSystemsIdentifierEthernetInterfacesIndexParams) WithIdentifier(identifier string) *GetSystemsIdentifierEthernetInterfacesIndexParams {
	o.Identifier = identifier
	return o
}

// WithIndex adds the index to the get systems identifier ethernet interfaces index params
func (o *GetSystemsIdentifierEthernetInterfacesIndexParams) WithIndex(index string) *GetSystemsIdentifierEthernetInterfacesIndexParams {
	o.Index = index
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemsIdentifierEthernetInterfacesIndexParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
