package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSystemParams creates a new GetSystemParams object
// with the default values initialized.
func NewGetSystemParams() *GetSystemParams {
	var ()
	return &GetSystemParams{}
}

/*GetSystemParams contains all the parameters to send to the API endpoint
for the get system operation typically these are written to a http.Request
*/
type GetSystemParams struct {

	/*Identifier
	  node identifier

	*/
	Identifier string
}

// WithIdentifier adds the identifier to the get system params
func (o *GetSystemParams) WithIdentifier(identifier string) *GetSystemParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
