package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSelLogServiceParams creates a new GetSelLogServiceParams object
// with the default values initialized.
func NewGetSelLogServiceParams() *GetSelLogServiceParams {
	var ()
	return &GetSelLogServiceParams{}
}

/*GetSelLogServiceParams contains all the parameters to send to the API endpoint
for the get sel log service operation typically these are written to a http.Request
*/
type GetSelLogServiceParams struct {

	/*Identifier*/
	Identifier string
}

// WithIdentifier adds the identifier to the get sel log service params
func (o *GetSelLogServiceParams) WithIdentifier(identifier string) *GetSelLogServiceParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSelLogServiceParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
