package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewGetSystemProcessorParams creates a new GetSystemProcessorParams object
// with the default values initialized.
func NewGetSystemProcessorParams() *GetSystemProcessorParams {
	var ()
	return &GetSystemProcessorParams{}
}

/*GetSystemProcessorParams contains all the parameters to send to the API endpoint
for the get system processor operation typically these are written to a http.Request
*/
type GetSystemProcessorParams struct {

	/*Identifier*/
	Identifier string
	/*Socket*/
	Socket string
}

// WithIdentifier adds the identifier to the get system processor params
func (o *GetSystemProcessorParams) WithIdentifier(identifier string) *GetSystemProcessorParams {
	o.Identifier = identifier
	return o
}

// WithSocket adds the socket to the get system processor params
func (o *GetSystemProcessorParams) WithSocket(socket string) *GetSystemProcessorParams {
	o.Socket = socket
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSystemProcessorParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	// path param socket
	if err := r.SetPathParam("socket", o.Socket); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
