package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSimpleStorageParams creates a new GetSimpleStorageParams object
// with the default values initialized.
func NewGetSimpleStorageParams() *GetSimpleStorageParams {
	var ()
	return &GetSimpleStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSimpleStorageParamsWithTimeout creates a new GetSimpleStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSimpleStorageParamsWithTimeout(timeout time.Duration) *GetSimpleStorageParams {
	var ()
	return &GetSimpleStorageParams{

		timeout: timeout,
	}
}

/*GetSimpleStorageParams contains all the parameters to send to the API endpoint
for the get simple storage operation typically these are written to a http.Request
*/
type GetSimpleStorageParams struct {

	/*Identifier*/
	Identifier string
	/*Index*/
	Index string

	timeout time.Duration
}

// WithIdentifier adds the identifier to the get simple storage params
func (o *GetSimpleStorageParams) WithIdentifier(identifier string) *GetSimpleStorageParams {
	o.Identifier = identifier
	return o
}

// WithIndex adds the index to the get simple storage params
func (o *GetSimpleStorageParams) WithIndex(index string) *GetSimpleStorageParams {
	o.Index = index
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *GetSimpleStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
