package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewListSimpleStorageParams creates a new ListSimpleStorageParams object
// with the default values initialized.
func NewListSimpleStorageParams() *ListSimpleStorageParams {
	var ()
	return &ListSimpleStorageParams{}
}

/*ListSimpleStorageParams contains all the parameters to send to the API endpoint
for the list simple storage operation typically these are written to a http.Request
*/
type ListSimpleStorageParams struct {

	/*Identifier*/
	Identifier string
}

// WithIdentifier adds the identifier to the list simple storage params
func (o *ListSimpleStorageParams) WithIdentifier(identifier string) *ListSimpleStorageParams {
	o.Identifier = identifier
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ListSimpleStorageParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
