package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd-redfish/models"
)

// NewModifyAccountParams creates a new ModifyAccountParams object
// with the default values initialized.
func NewModifyAccountParams() *ModifyAccountParams {
	var ()
	return &ModifyAccountParams{}
}

/*ModifyAccountParams contains all the parameters to send to the API endpoint
for the modify account operation typically these are written to a http.Request
*/
type ModifyAccountParams struct {

	/*Name*/
	Name string
	/*Payload*/
	Payload *models.ManagerAccount100ManagerAccount
}

// WithName adds the name to the modify account params
func (o *ModifyAccountParams) WithName(name string) *ModifyAccountParams {
	o.Name = name
	return o
}

// WithPayload adds the payload to the modify account params
func (o *ModifyAccountParams) WithPayload(payload *models.ManagerAccount100ManagerAccount) *ModifyAccountParams {
	o.Payload = payload
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *ModifyAccountParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if o.Payload == nil {
		o.Payload = new(models.ManagerAccount100ManagerAccount)
	}

	if err := r.SetBodyParam(o.Payload); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
