package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/emccode/gorackhd-redfish/models"
)

// NewPatchManagerParams creates a new PatchManagerParams object
// with the default values initialized.
func NewPatchManagerParams() *PatchManagerParams {
	var ()
	return &PatchManagerParams{}
}

/*PatchManagerParams contains all the parameters to send to the API endpoint
for the patch manager operation typically these are written to a http.Request
*/
type PatchManagerParams struct {

	/*Identifier*/
	Identifier string
	/*Payload*/
	Payload *models.Manager100Manager
}

// WithIdentifier adds the identifier to the patch manager params
func (o *PatchManagerParams) WithIdentifier(identifier string) *PatchManagerParams {
	o.Identifier = identifier
	return o
}

// WithPayload adds the payload to the patch manager params
func (o *PatchManagerParams) WithPayload(payload *models.Manager100Manager) *PatchManagerParams {
	o.Payload = payload
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *PatchManagerParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if o.Payload == nil {
		o.Payload = new(models.Manager100Manager)
	}

	if err := r.SetBodyParam(o.Payload); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
