package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// New creates a new redfish v1 API client.
func New(transport client.Transport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for redfish v1 API
*/
type Client struct {
	transport client.Transport
	formats   strfmt.Registry
}

/*
GetEventService retrieves list of policies used by event service listeners
*/
func (a *Client) GetEventService(params *GetEventServiceParams) (*GetEventServiceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetEventServiceParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetEventService",
		Method:             "GET",
		PathPattern:        "/EventService",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetEventServiceReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetEventServiceOK), nil
}

/*
GetManagerAccounts retrieves list of manager accounts
*/
func (a *Client) GetManagerAccounts(params *GetManagerAccountsParams) (*GetManagerAccountsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetManagerAccountsParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetManagerAccounts",
		Method:             "GET",
		PathPattern:        "/ManagerAccounts",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetManagerAccountsReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetManagerAccountsOK), nil
}

/*
GetManagerAccountsIdentifier retrieves a manager account by name
*/
func (a *Client) GetManagerAccountsIdentifier(params *GetManagerAccountsIdentifierParams) (*GetManagerAccountsIdentifierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetManagerAccountsIdentifierParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetManagerAccountsIdentifier",
		Method:             "GET",
		PathPattern:        "/ManagerAccounts/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetManagerAccountsIdentifierReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetManagerAccountsIdentifierOK), nil
}

/*
GetManagers retrieves list of management servers
*/
func (a *Client) GetManagers(params *GetManagersParams) (*GetManagersOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetManagersParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetManagers",
		Method:             "GET",
		PathPattern:        "/Managers",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetManagersReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetManagersOK), nil
}

/*
GetManagersIdentifier retrieves list of management servers
*/
func (a *Client) GetManagersIdentifier(params *GetManagersIdentifierParams) (*GetManagersIdentifierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetManagersIdentifierParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetManagersIdentifier",
		Method:             "GET",
		PathPattern:        "/Managers/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetManagersIdentifierReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetManagersIdentifierOK), nil
}

/*
GetRegistries unspecifieds
*/
func (a *Client) GetRegistries(params *GetRegistriesParams) (*GetRegistriesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRegistriesParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetRegistries",
		Method:             "GET",
		PathPattern:        "/Registries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetRegistriesReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetRegistriesOK), nil
}

/*
GetRoles retrieves list of roles for use in manager accounts
*/
func (a *Client) GetRoles(params *GetRolesParams) (*GetRolesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRolesParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetRoles",
		Method:             "GET",
		PathPattern:        "/Roles",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetRolesReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetRolesOK), nil
}

/*
GetRolesIdentifier retrieves a manager account role by name
*/
func (a *Client) GetRolesIdentifier(params *GetRolesIdentifierParams) (*GetRolesIdentifierOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetRolesIdentifierParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetRolesIdentifier",
		Method:             "GET",
		PathPattern:        "/Roles/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetRolesIdentifierReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetRolesIdentifierOK), nil
}

/*
GetSchemas unspecifieds
*/
func (a *Client) GetSchemas(params *GetSchemasParams) (*GetSchemasOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSchemasParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "GetSchemas",
		Method:             "GET",
		PathPattern:        "/Schemas",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSchemasReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSchemasOK), nil
}

/*
DoBootImage installs a boot image on a node

Perform the boot image installation specified in the post data arguments on  the system described by identifier

*/
func (a *Client) DoBootImage(params *DoBootImageParams) (*DoBootImageAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDoBootImageParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "doBootImage",
		Method:             "POST",
		PathPattern:        "/Systems/{identifier}/Actions/RackHD.BootImage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DoBootImageReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*DoBootImageAccepted), nil
}

/*
DoLogoutSession logouts of the session
*/
func (a *Client) DoLogoutSession(params *DoLogoutSessionParams) (*DoLogoutSessionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDoLogoutSessionParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "doLogoutSession",
		Method:             "DELETE",
		PathPattern:        "/SessionService/Sessions/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DoLogoutSessionReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*DoLogoutSessionOK), nil
}

/*
DoReset resets a node

Perform the reset specified in the post data arguments on the system described by identifier

*/
func (a *Client) DoReset(params *DoResetParams) (*DoResetAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDoResetParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "doReset",
		Method:             "POST",
		PathPattern:        "/Systems/{identifier}/Actions/ComputerSystem.Reset",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &DoResetReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*DoResetAccepted), nil
}

/*
GetChassis retrieves specific information for a physical component

Retrieves a detailed information catalog for the physical component  specified by identifier

*/
func (a *Client) GetChassis(params *GetChassisParams) (*GetChassisOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetChassisParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getChassis",
		Method:             "GET",
		PathPattern:        "/Chassis/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetChassisReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetChassisOK), nil
}

/*
GetPower retrieves power characteristics of a chassis

defines a collection of power elements contained within a resource.

*/
func (a *Client) GetPower(params *GetPowerParams) (*GetPowerOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetPowerParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getPower",
		Method:             "GET",
		PathPattern:        "/Chassis/{identifier}/Power",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetPowerReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetPowerOK), nil
}

/*
GetSelLogService retrieves list of the logs for a computer system

Defines a collection of SEL entries for the system described by identifier.

*/
func (a *Client) GetSelLogService(params *GetSelLogServiceParams) (*GetSelLogServiceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSelLogServiceParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSelLogService",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/LogServices/sel",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSelLogServiceReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSelLogServiceOK), nil
}

/*
GetSelLogServiceEntry retrieves log entry by log Id associated for log service

Defines a log entry specified by entryId within the LogService of the specified type for the system described by identifier

*/
func (a *Client) GetSelLogServiceEntry(params *GetSelLogServiceEntryParams) (*GetSelLogServiceEntryOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSelLogServiceEntryParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSelLogServiceEntry",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/LogServices/sel/Entries/{entryId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSelLogServiceEntryReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSelLogServiceEntryOK), nil
}

/*
GetServiceRoot retrieves list of root level resources

This object represents the root Redfish service.  All values for resources described  by this schema shall comply to the requirements as described in the Redfish specification. This object represents the root Redfish service.

*/
func (a *Client) GetServiceRoot(params *GetServiceRootParams) (*GetServiceRootOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetServiceRootParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getServiceRoot",
		Method:             "GET",
		PathPattern:        "/",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetServiceRootReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetServiceRootOK), nil
}

/*
GetSessionInfo retrieves session information
*/
func (a *Client) GetSessionInfo(params *GetSessionInfoParams) (*GetSessionInfoOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSessionInfoParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSessionInfo",
		Method:             "GET",
		PathPattern:        "/SessionService/Sessions/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSessionInfoReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSessionInfoOK), nil
}

/*
GetSessionService retrieves a list of sessions
*/
func (a *Client) GetSessionService(params *GetSessionServiceParams) (*GetSessionServiceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSessionServiceParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSessionService",
		Method:             "GET",
		PathPattern:        "/SessionService",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSessionServiceReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSessionServiceOK), nil
}

/*
GetSessions retrieves a sessions description
*/
func (a *Client) GetSessions(params *GetSessionsParams) (*GetSessionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSessionsParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSessions",
		Method:             "GET",
		PathPattern:        "/SessionService/Sessions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSessionsReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSessionsOK), nil
}

/*
GetSimpleStorage retrieves the simple storage collection by device identifier

Defines a collection of storage devices on the device specified by identifier that are present on the system described by identifier

*/
func (a *Client) GetSimpleStorage(params *GetSimpleStorageParams) (*GetSimpleStorageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSimpleStorageParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSimpleStorage",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/SimpleStorage/{index}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSimpleStorageReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSimpleStorageOK), nil
}

/*
GetSystem retrieves information for a specific computer systems physical and or virtual

defines a computer system and its respective properties.  A computer system represents a  machine (physical or virtual) and the local resources such as memory, cpu and other  devices that can be accessed from that machine.

*/
func (a *Client) GetSystem(params *GetSystemParams) (*GetSystemOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSystemParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSystem",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSystemReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSystemOK), nil
}

/*
GetSystemProcessor retrieves a specified processor for the specified system identifier

This represents the properties of a processor attached to a System.

*/
func (a *Client) GetSystemProcessor(params *GetSystemProcessorParams) (*GetSystemProcessorOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSystemProcessorParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSystemProcessor",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/Processors/{socket}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSystemProcessorReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSystemProcessorOK), nil
}

/*
GetSystemTasks retrieves list of tasks per system Id

This object represents the root Redfish service.
*/
func (a *Client) GetSystemTasks(params *GetSystemTasksParams) (*GetSystemTasksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetSystemTasksParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getSystemTasks",
		Method:             "GET",
		PathPattern:        "/TaskService/Oem/Tasks/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetSystemTasksReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetSystemTasksOK), nil
}

/*
GetTask retrieves a task entry by task Id

This object represents the root Redfish service.
*/
func (a *Client) GetTask(params *GetTaskParams) (*GetTaskOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetTaskParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getTask",
		Method:             "GET",
		PathPattern:        "/TaskService/Tasks/{identifier}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetTaskReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetTaskOK), nil
}

/*
GetThermal retrieves thermal characteristics of a chassis

defines a collection of thermal elements contained within a resource.

*/
func (a *Client) GetThermal(params *GetThermalParams) (*GetThermalOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetThermalParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "getThermal",
		Method:             "GET",
		PathPattern:        "/Chassis/{identifier}/Thermal",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &GetThermalReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetThermalOK), nil
}

/*
ListBootImage retrieves the list of boot image types for the specified compute node

Retrieve  a list of valid boot image types for the system described by identifier

*/
func (a *Client) ListBootImage(params *ListBootImageParams) (*ListBootImageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListBootImageParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listBootImage",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/Actions/RackHD.BootImage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListBootImageReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListBootImageOK), nil
}

/*
ListChassis retrieves list of physical components

Defines a collection of physical components managed by the service

*/
func (a *Client) ListChassis(params *ListChassisParams) (*ListChassisOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListChassisParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listChassis",
		Method:             "GET",
		PathPattern:        "/Chassis",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListChassisReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListChassisOK), nil
}

/*
ListLogService retrieves list of the logs for a computer system

Defines a collection of log services that are available for the system described by identifier

*/
func (a *Client) ListLogService(params *ListLogServiceParams) (*ListLogServiceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListLogServiceParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listLogService",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/LogServices",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListLogServiceReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListLogServiceOK), nil
}

/*
ListResetTypes retrieves the list of reset types for the specified compute node

Retrieve  a list of valid reset types for the system described by identifier

*/
func (a *Client) ListResetTypes(params *ListResetTypesParams) (*ListResetTypesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListResetTypesParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listResetTypes",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/Actions/ComputerSystem.Reset",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListResetTypesReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListResetTypesOK), nil
}

/*
ListSelLogServiceEntries retrieves list of the logs entries for associated for log service

Defines a collection of entries for the system described by identifier

*/
func (a *Client) ListSelLogServiceEntries(params *ListSelLogServiceEntriesParams) (*ListSelLogServiceEntriesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListSelLogServiceEntriesParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listSelLogServiceEntries",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/LogServices/sel/Entries",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListSelLogServiceEntriesReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListSelLogServiceEntriesOK), nil
}

/*
ListSimpleStorage retrieves the simple storage collection

Defines a collection of simple storage collections that are present on the system described by identifier

*/
func (a *Client) ListSimpleStorage(params *ListSimpleStorageParams) (*ListSimpleStorageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListSimpleStorageParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listSimpleStorage",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/SimpleStorage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListSimpleStorageReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListSimpleStorageOK), nil
}

/*
ListSystemProcessors retrieves the processor collection for the specified system identifier

defines a collection of processors contained within a resource.

*/
func (a *Client) ListSystemProcessors(params *ListSystemProcessorsParams) (*ListSystemProcessorsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListSystemProcessorsParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listSystemProcessors",
		Method:             "GET",
		PathPattern:        "/Systems/{identifier}/Processors",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListSystemProcessorsReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListSystemProcessorsOK), nil
}

/*
ListSystems retrieves list of computer systems

retrieve list of computer systems
*/
func (a *Client) ListSystems(params *ListSystemsParams) (*ListSystemsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListSystemsParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listSystems",
		Method:             "GET",
		PathPattern:        "/Systems",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListSystemsReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListSystemsOK), nil
}

/*
ListTasks retrieves list of all tasks

This object represents the root Redfish service.
*/
func (a *Client) ListTasks(params *ListTasksParams) (*ListTasksOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListTasksParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "listTasks",
		Method:             "GET",
		PathPattern:        "/TaskService/Tasks",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &ListTasksReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListTasksOK), nil
}

/*
PostSession creates a new session
*/
func (a *Client) PostSession(params *PostSessionParams) (*PostSessionCreated, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostSessionParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "postSession",
		Method:             "POST",
		PathPattern:        "/SessionService/Sessions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &PostSessionReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*PostSessionCreated), nil
}

/*
TaskServiceRoot retrieves list of all tasks

This object represents the root Redfish service.
*/
func (a *Client) TaskServiceRoot(params *TaskServiceRootParams) (*TaskServiceRootOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewTaskServiceRootParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "taskServiceRoot",
		Method:             "GET",
		PathPattern:        "/TaskService",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &TaskServiceRootReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*TaskServiceRootOK), nil
}

/*
Unimplemented retrieves account service information
*/
func (a *Client) Unimplemented(params *UnimplementedParams) (*UnimplementedOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUnimplementedParams()
	}

	result, err := a.transport.Submit(&client.Operation{
		ID:                 "unimplemented",
		Method:             "GET",
		PathPattern:        "/AccountService",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &UnimplementedReader{formats: a.formats},
	})
	if err != nil {
		return nil, err
	}
	return result.(*UnimplementedOK), nil
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport client.Transport) {
	a.transport = transport
}
