package redfish_v1

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-swagger/go-swagger/client"
	"github.com/go-swagger/go-swagger/errors"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
)

// NewUnimplementedParams creates a new UnimplementedParams object
// with the default values initialized.
func NewUnimplementedParams() *UnimplementedParams {
	var ()
	return &UnimplementedParams{}
}

/*UnimplementedParams contains all the parameters to send to the API endpoint
for the unimplemented operation typically these are written to a http.Request
*/
type UnimplementedParams struct {

	/*Identifier*/
	Identifier string
	/*Index*/
	Index string
}

// WithIdentifier adds the identifier to the unimplemented params
func (o *UnimplementedParams) WithIdentifier(identifier string) *UnimplementedParams {
	o.Identifier = identifier
	return o
}

// WithIndex adds the index to the unimplemented params
func (o *UnimplementedParams) WithIndex(index string) *UnimplementedParams {
	o.Index = index
	return o
}

// WriteToRequest writes these params to a swagger request
func (o *UnimplementedParams) WriteToRequest(r client.Request, reg strfmt.Registry) error {

	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	// path param index
	if err := r.SetPathParam("index", o.Index); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
