package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*EventDestination100HTTPHeaderProperty The value of the HTTP header is the property value.  The header name is the property name.

swagger:model EventDestination.1.0.0_HttpHeaderProperty
*/
type EventDestination100HTTPHeaderProperty interface{}
