package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"strconv"

	strfmt "github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*EventService100EventService This is the schema definition for the Event Service. It represents the properties for the service itself and has links to the actual list of subscriptions.

swagger:model EventService.1.0.0_EventService
*/
type EventService100EventService struct {

	/* at odata context

	Read Only: true
	*/
	AtOdataContext strfmt.URI `json:"@odata.context,omitempty"`

	/* at odata id

	Read Only: true
	*/
	AtOdataID strfmt.URI `json:"@odata.id,omitempty"`

	/* at odata type

	Read Only: true
	*/
	AtOdataType string `json:"@odata.type,omitempty"`

	/* actions
	 */
	Actions *EventService100EventServiceActions `json:"Actions,omitempty"`

	/* This is the number of attempts an event posting is retried before the subscription is terminated.

	Read Only: true
	*/
	DeliveryRetryAttempts float64 `json:"DeliveryRetryAttempts,omitempty"`

	/* This represents the number of seconds between retry attempts for sending any given Event

	Read Only: true
	*/
	DeliveryRetryIntervalSeconds float64 `json:"DeliveryRetryIntervalSeconds,omitempty"`

	/* Provides a description of this resource and is used for commonality  in the schema definitions.

	Read Only: true
	*/
	Description string `json:"Description,omitempty"`

	/* This is the types of Events that can be subscribed to.

	Read Only: true
	*/
	EventTypesForSubscription []string `json:"EventTypesForSubscription,omitempty"`

	/* Uniquely identifies the resource within the collection of like resources.

	Read Only: true
	*/
	ID string `json:"Id,omitempty"`

	/* The name of the resource or array element.

	Read Only: true
	*/
	Name string `json:"Name,omitempty"`

	/* This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.
	 */
	Oem ResourceOem `json:"Oem,omitempty"`

	/* This indicates whether this service is enabled.
	 */
	ServiceEnabled bool `json:"ServiceEnabled,omitempty"`

	/* status
	 */
	Status *ResourceStatus `json:"Status,omitempty"`

	/* This is a reference to a collection of Event Destination resources.

	Read Only: true
	*/
	Subscriptions *EventDestinationCollectionEventDestinationCollection `json:"Subscriptions,omitempty"`
}

// Validate validates this event service 1 0 0 event service
func (m *EventService100EventService) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateEventTypesForSubscription(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var eventService100EventServiceEventTypesForSubscriptionItemsEnum []interface{}

func (m *EventService100EventService) validateEventTypesForSubscriptionItemsEnum(path, location string, value string) error {
	if eventService100EventServiceEventTypesForSubscriptionItemsEnum == nil {
		var res []string
		if err := json.Unmarshal([]byte(`["StatusChange","ResourceUpdated","ResourceAdded","ResourceRemoved","Alert"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			eventService100EventServiceEventTypesForSubscriptionItemsEnum = append(eventService100EventServiceEventTypesForSubscriptionItemsEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, eventService100EventServiceEventTypesForSubscriptionItemsEnum); err != nil {
		return err
	}
	return nil
}

func (m *EventService100EventService) validateEventTypesForSubscription(formats strfmt.Registry) error {

	if swag.IsZero(m.EventTypesForSubscription) { // not required
		return nil
	}

	for i := 0; i < len(m.EventTypesForSubscription); i++ {

		// value enum
		if err := m.validateEventTypesForSubscriptionItemsEnum("EventTypesForSubscription"+"."+strconv.Itoa(i), "body", m.EventTypesForSubscription[i]); err != nil {
			return err
		}

	}

	return nil
}

/*EventService100EventServiceActions The Actions object contains the available custom actions on this resource.

swagger:model EventService100EventServiceActions
*/
type EventService100EventServiceActions struct {

	/* event service submit test event
	 */
	NrEventServiceSubmitTestEvent *EventService100SubmitTestEvent `json:"#EventService.SubmitTestEvent,omitempty"`

	/* oem
	 */
	Oem interface{} `json:"Oem,omitempty"`
}

// Validate validates this event service100 event service actions
func (m *EventService100EventServiceActions) Validate(formats strfmt.Registry) error {
	return nil
}
