package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*LogService100ClearLog log service 1 0 0 clear log

swagger:model LogService.1.0.0_ClearLog
*/
type LogService100ClearLog struct {

	/* Link to invoke action
	 */
	Target strfmt.URI `json:"target,omitempty"`

	/* Friendly action name
	 */
	Title string `json:"title,omitempty"`
}

// Validate validates this log service 1 0 0 clear log
func (m *LogService100ClearLog) Validate(formats strfmt.Registry) error {
	return nil
}
