package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*Manager100SerialConnectTypesSupported manager 1 0 0 serial connect types supported

swagger:model Manager.1.0.0_SerialConnectTypesSupported
*/
type Manager100SerialConnectTypesSupported string

// for schema
var manager100SerialConnectTypesSupportedEnum []interface{}

func (m Manager100SerialConnectTypesSupported) validateManager100SerialConnectTypesSupportedEnum(path, location string, value Manager100SerialConnectTypesSupported) error {
	if manager100SerialConnectTypesSupportedEnum == nil {
		var res []Manager100SerialConnectTypesSupported
		if err := json.Unmarshal([]byte(`["SSH","Telnet","IPMI","Oem"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			manager100SerialConnectTypesSupportedEnum = append(manager100SerialConnectTypesSupportedEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, manager100SerialConnectTypesSupportedEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this manager 1 0 0 serial connect types supported
func (m Manager100SerialConnectTypesSupported) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateManager100SerialConnectTypesSupportedEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
