package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Odata400Context odata 4 0 0 context

swagger:model odata.4.0.0_context
*/
type Odata400Context strfmt.URI

// Validate validates this odata 4 0 0 context
func (m Odata400Context) Validate(formats strfmt.Registry) error {
	return nil
}
