package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Odata400Type odata 4 0 0 type

swagger:model odata.4.0.0_type
*/
type Odata400Type string

// Validate validates this odata 4 0 0 type
func (m Odata400Type) Validate(formats strfmt.Registry) error {
	return nil
}
