package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Odata400ID odata 4 0 0 id

swagger:model odata.4.0.0_id
*/
type Odata400ID strfmt.URI

// Validate validates this odata 4 0 0 id
func (m Odata400ID) Validate(formats strfmt.Registry) error {
	return nil
}
