package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/go-swagger/go-swagger/errors"
)

/*Power100Voltage This is the base type for addressable members of an array.

swagger:model Power.1.0.0_Voltage
*/
type Power100Voltage struct {

	/* Below normal range but not yet fatal.

	Read Only: true
	*/
	LowerThresholdCritical float64 `json:"LowerThresholdCritical,omitempty"`

	/* Below normal range and is fatal

	Read Only: true
	*/
	LowerThresholdFatal float64 `json:"LowerThresholdFatal,omitempty"`

	/* Below normal range

	Read Only: true
	*/
	LowerThresholdNonCritical float64 `json:"LowerThresholdNonCritical,omitempty"`

	/* Maximum value for CurrentReading

	Read Only: true
	*/
	MaxReadingRange float64 `json:"MaxReadingRange,omitempty"`

	/* This is the identifier for the member within the collection.
	 */
	MemberID string `json:"MemberId,omitempty"`

	/* Minimum value for CurrentReading

	Read Only: true
	*/
	MinReadingRange float64 `json:"MinReadingRange,omitempty"`

	/* Voltage sensor name.

	Read Only: true
	*/
	Name string `json:"Name,omitempty"`

	/* This is the manufacturer/provider specific extension moniker used to divide the Oem object into sections.
	 */
	Oem ResourceOem `json:"Oem,omitempty"`

	/* Describes the area or device to which this voltage measurement applies.

	Read Only: true
	*/
	PhysicalContext PhysicalContext100PhysicalContext `json:"PhysicalContext,omitempty"`

	/* The current value of the voltage sensor.

	Read Only: true
	*/
	ReadingVolts float64 `json:"ReadingVolts,omitempty"`

	/* Describes the areas or devices to which this voltage measurement applies.

	Read Only: true
	*/
	RelatedItem []*Odata400IDRef `json:"RelatedItem,omitempty"`

	/* related item at odata count
	 */
	RelatedItemAtOdataCount Odata400Count `json:"RelatedItem@odata.count,omitempty"`

	/* related item at odata navigation link
	 */
	RelatedItemAtOdataNavigationLink *Odata400IDRef `json:"RelatedItem@odata.navigationLink,omitempty"`

	/* A numerical identifier to represent the voltage sensor

	Read Only: true
	*/
	SensorNumber float64 `json:"SensorNumber,omitempty"`

	/* status
	 */
	Status *ResourceStatus `json:"Status,omitempty"`

	/* Above normal range but not yet fatal.

	Read Only: true
	*/
	UpperThresholdCritical float64 `json:"UpperThresholdCritical,omitempty"`

	/* Above normal range and is fatal

	Read Only: true
	*/
	UpperThresholdFatal float64 `json:"UpperThresholdFatal,omitempty"`

	/* Above normal range

	Read Only: true
	*/
	UpperThresholdNonCritical float64 `json:"UpperThresholdNonCritical,omitempty"`
}

// Validate validates this power 1 0 0 voltage
func (m *Power100Voltage) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePhysicalContext(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateRelatedItem(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Power100Voltage) validatePhysicalContext(formats strfmt.Registry) error {

	if swag.IsZero(m.PhysicalContext) { // not required
		return nil
	}

	if err := m.PhysicalContext.Validate(formats); err != nil {
		return err
	}

	return nil
}

func (m *Power100Voltage) validateRelatedItem(formats strfmt.Registry) error {

	if swag.IsZero(m.RelatedItem) { // not required
		return nil
	}

	return nil
}
