package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*Processor100ProcessorType processor 1 0 0 processor type

swagger:model Processor.1.0.0_ProcessorType
*/
type Processor100ProcessorType string

// for schema
var processor100ProcessorTypeEnum []interface{}

func (m Processor100ProcessorType) validateProcessor100ProcessorTypeEnum(path, location string, value Processor100ProcessorType) error {
	if processor100ProcessorTypeEnum == nil {
		var res []Processor100ProcessorType
		if err := json.Unmarshal([]byte(`["CPU","GPU","FPGA","DSP","Accelerator","OEM"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			processor100ProcessorTypeEnum = append(processor100ProcessorTypeEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, processor100ProcessorTypeEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this processor 1 0 0 processor type
func (m Processor100ProcessorType) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateProcessor100ProcessorTypeEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
