package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Processor100ProcessorID processor 1 0 0 processor Id

swagger:model Processor.1.0.0_ProcessorId
*/
type Processor100ProcessorID struct {

	/* The effective Family for this processor

	Read Only: true
	*/
	EffectiveFamily string `json:"EffectiveFamily,omitempty"`

	/* The effective Model for this processor

	Read Only: true
	*/
	EffectiveModel string `json:"EffectiveModel,omitempty"`

	/* The contents of the Identification Registers (CPUID) for this processor

	Read Only: true
	*/
	IdentificationRegisters string `json:"IdentificationRegisters,omitempty"`

	/* The Microcode Information for this processor

	Read Only: true
	*/
	MicrocodeInfo string `json:"MicrocodeInfo,omitempty"`

	/* The Step value for this processor

	Read Only: true
	*/
	Step string `json:"Step,omitempty"`

	/* The Vendor Identification for this processor

	Read Only: true
	*/
	VendorID string `json:"VendorId,omitempty"`
}

// Validate validates this processor 1 0 0 processor Id
func (m *Processor100ProcessorID) Validate(formats strfmt.Registry) error {
	return nil
}
