package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-swagger/go-swagger/strfmt"
	"github.com/go-swagger/go-swagger/swag"

	"github.com/go-swagger/go-swagger/errors"
)

/*RackHDResetAction rack h d reset action

swagger:model RackHD_ResetAction
*/
type RackHDResetAction struct {

	/* reset type
	 */
	ResetType ResourceResetType `json:"reset_type,omitempty"`
}

// Validate validates this rack h d reset action
func (m *RackHDResetAction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateResetType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *RackHDResetAction) validateResetType(formats strfmt.Registry) error {

	if swag.IsZero(m.ResetType) { // not required
		return nil
	}

	if err := m.ResetType.Validate(formats); err != nil {
		return err
	}

	return nil
}
