package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*RackHDBootImageNetworkAddress rack h d boot image network address

swagger:model RackHD.BootImage_NetworkAddress
*/
type RackHDBootImageNetworkAddress struct {

	/* gateway
	 */
	Gateway string `json:"gateway,omitempty"`

	/* ip addr
	 */
	IPAddr string `json:"ipAddr,omitempty"`

	/* netmask
	 */
	Netmask string `json:"netmask,omitempty"`

	/* vlan Id
	 */
	VlanID string `json:"vlanId,omitempty"`
}

// Validate validates this rack h d boot image network address
func (m *RackHDBootImageNetworkAddress) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
