package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

/*RackHDBootImageUsers rack h d boot image users

swagger:model RackHD.BootImage_Users
*/
type RackHDBootImageUsers struct {

	/* name
	 */
	Name string `json:"name,omitempty"`

	/* password
	 */
	Password string `json:"password,omitempty"`

	/* ssh key
	 */
	SSHKey string `json:"sshKey,omitempty"`

	/* uid
	 */
	UID float64 `json:"uid,omitempty"`
}

// Validate validates this rack h d boot image users
func (m *RackHDBootImageUsers) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
