package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*ResourceID Uniquely identifies the resource within the collection of like resources.

swagger:model Resource_Id
*/
type ResourceID string

// Validate validates this resource Id
func (m ResourceID) Validate(formats strfmt.Registry) error {
	return nil
}
