package models

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*RoleRole role role

swagger:model Role_Role
*/
type RoleRole struct {
	Role100Role
}

// Validate validates this role role
func (m *RoleRole) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Role100Role.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
