package models

import "github.com/go-swagger/go-swagger/strfmt"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*SimpleStorage100Device simple storage 1 0 0 device

swagger:model SimpleStorage.1.0.0_Device
*/
type SimpleStorage100Device struct {

	/* The name of the manufacturer of this device

	Read Only: true
	*/
	Manufacturer string `json:"Manufacturer,omitempty"`

	/* The product model number of this device

	Read Only: true
	*/
	Model string `json:"Model,omitempty"`

	/* The name of the resource or array element.

	Required: true
	Read Only: true
	*/
	Name string `json:"Name"`

	/* oem
	 */
	Oem ResourceOem `json:"Oem,omitempty"`

	/* status
	 */
	Status *ResourceStatus `json:"Status,omitempty"`
}

// Validate validates this simple storage 1 0 0 device
func (m *SimpleStorage100Device) Validate(formats strfmt.Registry) error {
	return nil
}
