package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Status403 The server recognized the credentials in the request, but those credentials do not  possess authorization to perform this request.


swagger:model status_403
*/
type Status403 interface{}
