package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*Status202 The request has been accepted for processing, but the processing has not been completed.  The Location header shall be set to the URI of a Task resource that can later be queried  to determine the status of the operation. A representation of the Task resource may be  included in the response body.


swagger:model status_202
*/
type Status202 interface{}
