package models

import (
	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/strfmt"
)

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

/*TaskTask task task

swagger:model Task_Task
*/
type TaskTask struct {
	Task100Task
}

// Validate validates this task task
func (m *TaskTask) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.Task100Task.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
