package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-swagger/go-swagger/strfmt"

	"github.com/go-swagger/go-swagger/errors"
	"github.com/go-swagger/go-swagger/httpkit/validate"
)

/*VirtualMedia100ConnectedVia virtual media 1 0 0 connected via

swagger:model VirtualMedia.1.0.0_ConnectedVia
*/
type VirtualMedia100ConnectedVia string

// for schema
var virtualMedia100ConnectedViaEnum []interface{}

func (m VirtualMedia100ConnectedVia) validateVirtualMedia100ConnectedViaEnum(path, location string, value VirtualMedia100ConnectedVia) error {
	if virtualMedia100ConnectedViaEnum == nil {
		var res []VirtualMedia100ConnectedVia
		if err := json.Unmarshal([]byte(`["NotConnected","URI","Applet","Oem"]`), &res); err != nil {
			return err
		}
		for _, v := range res {
			virtualMedia100ConnectedViaEnum = append(virtualMedia100ConnectedViaEnum, v)
		}
	}
	if err := validate.Enum(path, location, value, virtualMedia100ConnectedViaEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this virtual media 1 0 0 connected via
func (m VirtualMedia100ConnectedVia) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateVirtualMedia100ConnectedViaEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
